<?PHP
    //Static functions for central Color storage

function GetColorList() {
    $colors = array(
        "&" => array('hex'=>"#FFFFFF",'class' => "colLtWhite"),
        "j" => array('hex'=>"#DDDDDD",'class' => "colMdGrey"),
        "7" => array('hex'=>"#B0B0B0",'class' => "colDkWhite"),
        ")" => array('hex'=>"#999999",'class' => "colLtBlack"),
        "B" => array('hex'=>"#707070",'class' => "colmousegrey"),
		"(" => array('hex'=>"#575757",'class' => "colsparkgray"),
        "~" => array('hex'=>"#000000",'class' => "colBlack"), 
        "X" => array('hex'=>"#F5F5DC",'class' => "colbeige"),
        "a" => array('hex'=>"#FFF28E",'class' => "collightyellow"),
		"^" => array('hex'=>"#FFFF00",'class' => "colLtYellow"),
		"s" => array('hex'=>"#FFBF26",'class' => "collightorange"),
		"Q" => array('hex'=>"#FF9900",'class' => "colLtOrange"),
		"A" => array('hex'=>"#FF6600",'class' => "coldarkorange"),
		"\$" => array('hex'=>"#FF0000",'class' => "colLtRed"),
		"[" => array('hex'=>"#D10000",'class' => "colbrickred"),
		"U" => array('hex'=>"#AE2722",'class' => "colclottedred"),
		"C" => array('hex'=>"#8B3626",'class' => "collightrottenred"),
		"4" => array('hex'=>"#B00000",'class' => "colDkRed"),
        "8" => array('hex'=>"#780000",'class' => "colMedRed"),
		"]" => array('hex'=>"#8A023F",'class' => "colsweetred"),
		"f" => array('hex'=>"#B9034C",'class' => "colcandyred"),
		"g" => array('hex'=>"#aaff99",'class' => "colXLtGreen"),
		"G" => array('hex'=>"#8CFF63",'class' => "colpeppermint"),
		"@" => array('hex'=>"#00FF00",'class' => "colLtGreen"),
        "2" => array('hex'=>"#00B000",'class' => "colDkGreen"),
		"h" => array('hex'=>"#035900",'class' => "colfir"),
		"W" => array('hex'=>"#457A00",'class' => "coldarkfir"),
		"z" => array('hex'=>"#669900",'class' => "collightfir"),
		"K" => array('hex'=>"#8FBC8F",'class' => "coldarkseagreen"),
		"?" => array('hex'=>"#2d8574",'class' => "colblueishgreen"),
		"3" => array('hex'=>"#00B0B0",'class' => "colDkCyan"),
        "k" => array('hex'=>"#7FFFD4",'class' => "colaquamarine"),
		"N" => array('hex'=>"#5fd5bc",'class' => "colflashymint"),
		"#" => array('hex'=>"#00FFFF",'class' => "colLtCyan"),
		"Z" => array('hex'=>"#59CEFD",'class' => "colskyblue"),
		"L" => array('hex'=>"#0099FF",'class' => "colLtLinkBlue"),
        "l" => array('hex'=>"#006BB3",'class' => "colDkLinkBlue"),
		"+" => array('hex'=>"#2f4386",'class' => "colmoredarkblue"),
        "!" => array('hex'=>"#0000FF",'class' => "colLtBlue"),
        "J" => array('hex'=>"#0000F0",'class' => "colMdBlue"),
        "1" => array('hex'=>"#0000B0",'class' => "colDkBlue"),
        "p" => array('hex'=>"#FFA07A",'class' => "collightsalmon"),
        "P" => array('hex'=>"#FA8072",'class' => "colsalmon"),
		"€" => array('hex'=>"#FD342F",'class' => "coltomatoered"),
		"R" => array('hex'=>"#EEBBEE",'class' => "colRose"),
		"r" => array('hex'=>"#DC79FF",'class' => "colbabypink"),
		"%" => array('hex'=>"#FF00FF",'class' => "colLtMagenta"),
        "5" => array('hex'=>"#B000CC",'class' => "colDkMagenta"),
		"u" => array('hex'=>"#800099",'class' => "coldarklilac"),
		"*" => array('hex'=>"#5180E5",'class' => "colblueishpurple"),
		"-" => array('hex'=>"#A390EE",'class' => "colsweetspurple"),
		"v" => array('hex'=>"#AABBEE",'class' => "coliceviolet"),
        "V" => array('hex'=>"#9A5BEE",'class' => "colBlueViolet"),
		"_" => array('hex'=>"#7F68DF",'class' => "colelearapurple"),
		"d" => array('hex'=>"#7373FF",'class' => "collightlilac"),
		"m" => array('hex'=>"#F5DEB3",'class' => "colwheat"),
        "M" => array('hex'=>"#D2B48C",'class' => "coltan"),
		"9" => array('hex'=>"#AE8F68",'class' => "colclaybrown"),
		"x" => array('hex'=>"#DEB887",'class' => "colburlywood"),
        "E" => array('hex'=>"#B07878",'class' => "colLtRust"),
        "e" => array('hex'=>"#8D6060",'class' => "colDkRust"),
		"D" => array('hex'=>"#815E39",'class' => "colmiddlebrown"),
		"T" => array('hex'=>"#6b563f",'class' => "colDkBrown"),
		"I" => array('hex'=>"#523b34",'class' => "colrottenred"),
		"q" => array('hex'=>"#994400",'class' => "colDkOrange"),
        "t" => array('hex'=>"#F8DB83",'class' => "colLtBrown"),
        "y" => array('hex'=>"#F0E68C",'class' => "colkhaki"),
        "Y" => array('hex'=>"#BDB76B",'class' => "coldarkkhaki"),
        "6" => array('hex'=>"#B0B000",'class' => "colDkYellow"),
		"S" => array('hex'=>"#997F99",'class' => "collightmallow"),
		"o" => array('hex'=>"#7F667F",'class' => "colmallow"),
		"O" => array('hex'=>"#664C66",'class' => "coldarkmallow"),
	);

    return $colors;
}
?>